### ISSUE TITLE
Opencv Pull request

### ISSUE THREAD

**Issue by LaurentBerger** [vrabaud/gPb#8]
Hi,

I'm interested by this code and other opencv users too (http://answers.opencv.org/question/123328/is-gpb-available-in-opencv)
Do you want to push you code in Opencv ?
 If you haven't got enough time I can push your code in opencv if you are agree of course.

regards

**Comment by vrabaud** [comment]
So, this code is from a GSOC. There are still some parts that depend on Matlab no ? That's why we couldn't merge it upstream. Do you think it is?

**Comment by PkLab** [comment]
It looks opencv/opencv#4494

> there is licensing issues.

**Comment by LaurentBerger** [comment]
Thanks for your answer
I think it is possible but it won't take 5 minutes ...
